/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#885500",
        "on-secondary": "#003824",
        "background": "#111318",
        "surface-bright": "#37393e",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#2f3035",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#dad7ff",
        "surface-tint": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary-fixed-variant": "#005236",
        "secondary-container": "#00a572",
        "outline": "#918fa1",
        "primary-container": "#4f46e5",
        "on-error": "#690005",
        "surface-container-high": "#282a2e",
        "on-secondary-container": "#00311f",
        "primary-fixed-dim": "#c3c0ff",
        "secondary": "#4edea3",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "error-container": "#93000a",
        "primary": "#c3c0ff",
        "on-tertiary-container": "#ffd4a4",
        "error": "#ffb4ab",
        "inverse-primary": "#4d44e3",
        "on-surface-variant": "#c7c4d8",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#333539",
        "secondary-fixed": "#6ffbbe",
        "on-surface": "#e2e2e8",
        "inverse-surface": "#e2e2e8",
        "outline-variant": "#464555",
        "on-background": "#e2e2e8",
        "surface-dim": "#111318",
        "surface": "#111318",
        "surface-variant": "#333539",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "on-primary": "#1d00a5",
        "surface-container-lowest": "#0c0e12"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "40px",
        "xs": "4px",
        "gutter": "24px",
        "md": "24px",
        "xl": "64px",
        "base": "8px",
        "margin-safe": "32px",
        "sm": "12px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
