namespace ProductIQ.UnitTests.Products;

using System;
using System.Threading.Tasks;
using FluentAssertions;
using ProductIQ.Application.Common.Models;
using ProductIQ.Application.DTOs;
using ProductIQ.Application.Services;
using ProductIQ.Domain.Entities;
using ProductIQ.UnitTests.Common;
using Xunit;

public class ProductServiceTests
{
    [Fact]
    public async Task CreateProductAsync_WithAutoGeneratedAsin_ShouldPrefixPIQAndPersist()
    {
        using var context = TestDbContextFactory.Create();
        var sut = new ProductService(context);

        var request = new CreateProductRequest
        {
            Name = "Ergonomic Mechanical Keyboard",
            Brand = "Keychron",
            Category = "Computer Accessories",
            Price = 119.99m,
            Currency = "USD"
        };

        var created = await sut.CreateProductAsync(request);

        created.Should().NotBeNull();
        created.Id.Should().NotBeEmpty();
        created.AmazonItemId.Should().StartWith("PIQ-");
        created.Name.Should().Be("Ergonomic Mechanical Keyboard");
        created.Brand.Should().Be("Keychron");
        created.Price.Should().Be(119.99m);

        var persisted = await context.Products.FindAsync(created.Id);
        persisted.Should().NotBeNull();
        persisted!.AmazonItemId.Should().Be(created.AmazonItemId);
    }

    [Fact]
    public async Task CreateProductAsync_WithExplicitAsin_ShouldPersistProvidedAsin()
    {
        using var context = TestDbContextFactory.Create();
        var sut = new ProductService(context);

        var request = new CreateProductRequest
        {
            Name = "Explicit Asin Product",
            AmazonItemId = "B00EXPLICIT1"
        };

        var created = await sut.CreateProductAsync(request);

        created.AmazonItemId.Should().Be("B00EXPLICIT1");
        var persisted = await context.Products.FindAsync(created.Id);
        persisted!.AmazonItemId.Should().Be("B00EXPLICIT1");
    }

    [Fact]
    public async Task CreateProductAsync_WithExistingAsin_ShouldAppendUniqueSuffix()
    {
        using var context = TestDbContextFactory.Create();
        context.Products.Add(new Product
        {
            AmazonItemId = "B00EXISTING1",
            Name = "Existing Product"
        });
        await context.SaveChangesAsync();

        var sut = new ProductService(context);

        var request = new CreateProductRequest
        {
            Name = "Second Product with same Asin",
            AmazonItemId = "B00EXISTING1"
        };

        var created = await sut.CreateProductAsync(request);

        created.AmazonItemId.Should().StartWith("B00EXISTING1-");
        created.AmazonItemId.Should().NotBe("B00EXISTING1");
    }

    [Fact]
    public async Task CreateProductAsync_WithMainImage_ShouldCreateAssociatedProductImage()
    {
        using var context = TestDbContextFactory.Create();
        var sut = new ProductService(context);

        var request = new CreateProductRequest
        {
            Name = "Product With Main Image",
            MainImageUrl = "https://images.example.com/item.jpg"
        };

        var created = await sut.CreateProductAsync(request);

        created.MainImageUrl.Should().Be("https://images.example.com/item.jpg");
        created.Images.Should().HaveCount(1);
        created.Images[0].IsMain.Should().BeTrue();
        created.Images[0].Url.Should().Be("https://images.example.com/item.jpg");
    }

    [Fact]
    public async Task CreateProductAsync_WithAttributes_ShouldCreateProductAttributes()
    {
        using var context = TestDbContextFactory.Create();
        var sut = new ProductService(context);

        var request = new CreateProductRequest
        {
            Name = "Product With Attributes",
            Brand = "Rivet",
            Color = "Emerald Green",
            Material = "Velvet"
        };

        var created = await sut.CreateProductAsync(request);

        created.Attributes.Should().HaveCount(3);
        created.Attributes.Should().Contain(a => a.Key == "Brand" && a.Value == "Rivet");
        created.Attributes.Should().Contain(a => a.Key == "Color" && a.Value == "Emerald Green");
        created.Attributes.Should().Contain(a => a.Key == "Material" && a.Value == "Velvet");
    }

    [Fact]
    public async Task GetProductByIdAsync_WithExistingProduct_ShouldReturnDetailDto()
    {
        using var context = TestDbContextFactory.Create();
        var product = new Product
        {
            AmazonItemId = "B00FINDME01",
            Name = "Findable Product",
            Brand = "Solimo"
        };
        context.Products.Add(product);
        await context.SaveChangesAsync();

        var sut = new ProductService(context);

        var found = await sut.GetProductByIdAsync(product.Id);

        found.Should().NotBeNull();
        found!.Id.Should().Be(product.Id);
        found.Name.Should().Be("Findable Product");
        found.Brand.Should().Be("Solimo");
    }

    [Fact]
    public async Task GetProductByIdAsync_WithNonExistentProduct_ShouldReturnNull()
    {
        using var context = TestDbContextFactory.Create();
        var sut = new ProductService(context);

        var found = await sut.GetProductByIdAsync(Guid.NewGuid());

        found.Should().BeNull();
    }

    [Fact]
    public async Task GetProductsAsync_WithPaginationAndFilter_ShouldReturnPagedResults()
    {
        using var context = TestDbContextFactory.Create();
        for (var i = 1; i <= 15; i++)
        {
            context.Products.Add(new Product
            {
                AmazonItemId = $"B00PAGINATE{i:D2}",
                Name = $"Product Number {i}",
                Brand = i % 2 == 0 ? "BrandAlpha" : "BrandBeta"
            });
        }
        await context.SaveChangesAsync();

        var sut = new ProductService(context);

        var parameters = new ProductQueryParameters
        {
            Page = 1,
            PageSize = 5,
            Brand = "BrandAlpha"
        };

        var response = await sut.GetProductsAsync(parameters);

        response.Should().NotBeNull();
        response.TotalCount.Should().Be(7);
        response.Items.Should().HaveCount(5);
        response.Items.Should().OnlyContain(p => p.Brand == "BrandAlpha");
    }
}
